---
# Install collections with `curl -sL git.io/elgalu | bash`
#
collections:
  - name: ansible.posix
    version: 1.1.1

  - name: community.general
    version: 3.0.0

# TODO: move to Ansible>=2.9.10
roles:
  # https://github.com/dev-sec/ansible-collection-hardening
  # https://galaxy.ansible.com/devsec/hardening
  - src: dev-sec.ssh-hardening
    version: "6.1.3"

  # https://github.com/dev-sec/ansible-collection-hardening/blob/a075af2/roles/os_hardening/templates/etc/login.defs.j2
  # Keeping a fork due to:
  #   https://github.com/dev-sec/ansible-collection-hardening/pull/461
  - src: https://github.com/elgalu/ansible-collection-hardening
    name: dev-sec.os-hardening
    version: "a431e13e0b0e441dadd09970430acaff64970cd5"

  # Keeping a fork of DeepOps.users due to
  #   https://github.com/DeepOps/ansible-role-users/pull/1
  #   https://github.com/DeepOps/ansible-role-users/issues/2
  - src: https://github.com/elgalu/ansible-role-users
    name: DeepOps.users
    version: "756685c7bd05ed2c33f30fac3683e2ede0009112"

  - src: https://github.com/DeepOps/ansible-role-hosts.git
    name: DeepOps.hosts
    version: "8311d6ecfe39b665a06d1fc55502c6916e9ab5ce"

  # TODO: Upgrade to 2.3.0
  - src: geerlingguy.ntp
    version: "1.6.3"

  # - src: andrewrothstein.miniconda
  #   version: "v6.1.2"

  - src: https://github.com/ansible-collections/community.docker
    name: community.docker
    version: "a0f2091e6a75318192f4e4813be22963d0ec632f" # "1.8.0"

  # https://galaxy.ansible.com/geerlingguy/docker
  - src: geerlingguy.docker
    version: "3.1.2"

  # Stock nvidia_driver role doesn't have the latest version, fork.
  # Test with
  #
  #   grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/*
  #
  # Wrong (18.04)
  #   /etc/apt/sources.list.d/nvidia-docker.list:deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
  #   /etc/apt/sources.list.d/nvidia-docker.list:deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /
  #   /etc/apt/sources.list.d/nvidia-docker.list:deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /
  #
  # Good:
  #   /etc/apt/sources.list.d/nvidia-cuda.list:deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64 /
  #   /etc/apt/sources.list.d/nvidia-cudnn.list:deb http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64 /
  #
  - src: https://github.com/elgalu/ansible-role-nvidia-driver
    name: nvidia.nvidia_driver
    version: "07a277c4df44eb63ec1a9d7f5a4cc1e3d5b4888a"

  - src: https://github.com/elgalu/ansible-role-nvidia-docker
    name: nvidia.nvidia_docker
    version: "da6313c66f52c5ab07e21b20a3215d94994fd2b1"

  - src: nvidia.enroot
    version: "v0.4.0"

  # TODO: Install https://github.com/geerlingguy/ansible-role-aws-inspector

  # - src: geerlingguy.filebeat
  #   version: "2.0.1"

  # - src: geerlingguy.logstash
  #   version: "4.0.0"

  # - src: geerlingguy.elasticsearch
  #   version: "3.0.1"

  # - src: geerlingguy.java
  #   version: "1.9.5"

  # - src: geerlingguy.kibana
  #   version: "3.2.1"

  # - src: https://github.com/DeepOps/ansible-maas.git
  #   name: ansible-maas
  #   version: "632fe9bd1e048b9abb717621dc2d76b19614327b"

  - src: https://github.com/DeepOps/ansible-role-chrony
    name: DeepOps.chrony
    version: "c9022153036dfdde4e2b313aecde4a46cd6f6687"

  - src: https://github.com/OSC/ood-ansible.git
    name: ood-ansible
    version: "d7e677fa6355a4d4b27396750e8216825c755177"

  - src: gantsign.golang
    version: 2.6.5

  - src: https://github.com/abims-sbr/ansible-singularity
    name: singularity
    version: "7857fae9351310b91af3473661d19492379af4e8"

  # For now just to set `DNSStubListener=no`
  # DNSStubListener: a DNS stub resolver will listen for UDP requests on address 127.0.0.53 port 53.
  # If "yes" (the default), the stub listens for both UDP and TCP requests.
  # If "no", the stub listener is disabled.
  - src: https://github.com/elgalu/ansible-role-systemd-resolved
    name: aisbergg.systemd-resolved
    version: "226dab32895f629aa3a138c91507ad6377547096"

  - src: https://github.com/marcinpraczko/ansible-goss-install
    name: marcinpraczko.goss-install
    version: "c33e4ac7a9ea45cdc719e19a40c4347e705ab747"
