---
- name: Ubuntu | remove ppa
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    state: absent

- name: Ubuntu | add pin file
  copy:
    src: "cuda-ubuntu.pin"
    dest: "/etc/apt/preferences.d/cuda-repository-pin-600"
    owner: "root"
    group: "root"
    mode: 0644
