---
spack_repo: "https://github.com/spack/spack.git"
spack_install_dir: "/sw/spack"
spack_version: "v0.16.2"
spack_user: "root"
spack_group: "root"

spack_ubuntu_deps:
  - "gcc-7"
  - "gfortran-7"
  - "make"
  - "git"

spack_build_packages: false
spack_default_packages:
  - "cuda@11.2.152"
  - "openmpi@4.1.1 +cuda +pmi schedulers=auto"
