---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb-server
    - python3-mysqldb
    - s-nail
    - ssmtp
  when: ansible_os_family == "Debian"

- name: setup slurm db user
  mysql_user:
    name: "{{ slurm_db_username }}"
    password: "{{ slurm_db_password }}"
    host: localhost
    priv: "*.*:USAGE/slurm_acct_db.*:ALL"
    state: present

- name: create slurm directories
  file:
    path: "{{ item }}"
    state: directory
    owner: slurm
    mode: 0755
  with_items:
    - "{{ slurm_config_dir }}"
    - /var/spool/slurm/ctld
    - /var/log/slurm

# Also fixed:
#   [106] Role name {0} does not match ``^[a-z][a-z0-9_]+$`` pattern.
#   https://ansible-lint.readthedocs.io/en/latest/default_rules.html#role-name
#
#   [204] Lines should be no longer than 160 chars.
#
#   [206] Variables should have spaces before and after: {{ var_name }}
#   https://ansible-lint.readthedocs.io/en/latest/default_rules.html#var-spacing
#
#   [301] Commands should not change things if nothing needs doing
#   https://ansible-lint.readthedocs.io/en/latest/default_rules.html#no-changed-when
#
#   [302] Using command rather than an argument to e.g. file
#   https://ansible-lint.readthedocs.io/en/latest/default_rules.html#deprecated-command-syntax
#
#   [305] Use shell only when shell functionality is required
#   https://blog.confirm.ch/ansible-modules-shell-vs-command/
#   > The command module is more secure, because it will not be affected by the user’s environment.
#   https://ansible-lint.readthedocs.io/en/latest/default_rules.html#command-instead-of-shell
#
#   [306] Shells that use pipes should set the pipefail option
#   https://ansible-lint.readthedocs.io/en/latest/default_rules.html#risky-shell-pipe
#
#   [401] Git checkouts must contain explicit version
#   https://ansible-lint.readthedocs.io/en/latest/default_rules.html#git-latest
#
#   [403] Package installs should not use latest
#   https://ansible-lint.readthedocs.io/en/latest/default_rules.html#package-latest
#
#   [502] All tasks should be named
#   https://ansible-lint.readthedocs.io/en/latest/default_rules.html#unnamed-task
#
#   [601] Don't compare to literal True/False
#   https://ansible-lint.readthedocs.io/en/latest/default_rules.html#literal-compare
#
#   [602] Don't compare to empty string
#   https://ansible-lint.readthedocs.io/en/latest/default_rules.html#empty-string-compare
#
#   [701] Role info should contain description
#   [701] No 'galaxy_info' found
#
#   [702] Use 'galaxy_tags' rather than 'categories'

- name: create slurm HA directory
  file:
    path: "{{ slurm_ha_state_save_location }}"
    state: directory
    owner: slurm
    # [208] missing or unsupported `mode` parameter can cause unexpected file
    # permissions based on version of Ansible being used.
    # https://ansible-lint.readthedocs.io/en/latest/default_rules.html#risky-file-permissions
    mode: 0755
  # [102] `when` is a raw Jinja2 expression, remove redundant {{ }} from variable(s).
  # https://ansible-lint.readthedocs.io/en/latest/default_rules.html#no-jinja-when
  when: slurm_enable_ha|default(false)

- name: configure slurm.conf
  template:
    src: "{{ slurm_conf_template }}"
    dest: "{{ slurm_config_dir }}/slurm.conf"
    mode: 0644
  notify:
    - restart slurmctld
  tags:
    - config

- name: configure slurmdbd.conf
  template:
    src: "{{ slurm_dbd_conf_template }}"
    dest: "{{ slurm_config_dir }}/slurmdbd.conf"
    owner: "{{ slurm_username }}"
    mode: 0600
  notify:
    - restart slurmdbd
  tags:
    - config

- name: restart slurmdbd
  systemd:
    name: slurmdbd
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: wait for slurmdbd to be available
  wait_for:
    port: 6819
    delay: 5

- name: create cluster
  command: sacctmgr -i add cluster {{ slurm_cluster_name }}
  register: create_cluster_result
  failed_when: "create_cluster_result.rc != 0 and 'already exists' not in create_cluster_result.stdout"
  changed_when: "'already exists' not in create_cluster_result.stdout"
  environment:
    PATH: "{{ slurm_install_prefix }}/bin:{{ ansible_env.PATH }}"
  run_once: true

- name: create account
  command: sacctmgr -i add account compute-account Description="Compute Accounts" Organization="Prestige"
  register: create_account_result
  failed_when: "create_account_result.rc != 0 and 'Nothing new added' not in create_account_result.stdout"
  changed_when: "'Nothing new added' not in create_account_result.stdout"
  environment:
    PATH: "{{ slurm_install_prefix }}/bin:{{ ansible_env.PATH }}"

- name: create users
  command: sacctmgr -i create user {{ item }} account=compute-account adminlevel=None
  register: create_user_result
  failed_when: "create_user_result.rc != 0 and 'Nothing new added' not in create_user_result.stdout"
  changed_when: "'Nothing new added' not in create_user_result.stdout"
  with_items:
    - "{{ user }}"
  environment:
    PATH: "{{ slurm_install_prefix }}/bin:{{ ansible_env.PATH }}"

- name: clear slurm state when downgrading
  command: slurmctld -i
  when: slurm_downgrade
  environment:
    PATH: "{{ slurm_install_prefix }}/bin:{{ ansible_env.PATH }}"

- name: wait for slurmctld to start
  pause:
    seconds: 20
  when: slurm_downgrade

- name: kill slurmctld
  command: killall slurmctld
  ignore_errors: yes
  when: slurm_downgrade

- name: restart slurmctld
  systemd:
    name: slurmctld
    state: restarted
    enabled: yes
    daemon-reload: yes
