---
- name: Hide GPUs for regular user logins via sshd.service.
  shell: |
    __device_allow="$(systemctl show sshd.service -p DeviceAllow)"
    __nvidiactl_case_insensitive_match="nvidiactl"

    if [ "${__device_allow,,}" = "${__nvidiactl_case_insensitive_match,,}" ]; then
      echo "INFO: sshd.service already contains '${__device_allow}' in DeviceAllow"
    else
      systemctl set-property sshd.service DeviceAllow="/dev/nvidiactl"
    fi
  args:
    creates: "{{ '/etc/systemd/system.control/ssh.service.d/50-DeviceAllow.conf' }}"
  when: is_controller
  tags:
    - config

- name: Patch lastuserjob epilog.
  blockinfile:
    path: /etc/slurm/epilog.d/40-lastuserjob-processes
    block: |

      if grep -q -w "$SLURM_JOB_USER" /etc/slurm/localusers.backup ; then
          exit 0  # don't revoke access for these users
      fi

    insertafter: "^set -ex"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (ansible-role-slurm)"
  when: is_controller
  notify: restart slurmctld
  tags:
    - config
