---
- name: create slurm user home
  file:
    path: "{{ slurm_user_home }}"
    recurse: yes
    state: directory
    mode: 0755

- name: create slurm user
  user:
    name: slurm
    state: present
    system: yes
    home: "{{ slurm_user_home }}"
    uid: "{{ slurm_user_uid }}"
