---
# Chrony will ensure that the clocks of all your servers are up to sync and can be used to sync with an internal server
- hosts: all
  become: true
  tasks:
    - name: Configure Chrony client
      include_role:
        name: DeepOps.chrony

    - name: Set timezone
      # noqa 305 Use shell only when shell functionality is required
      # noqa 301 https://ansible-lint.readthedocs.io/en/latest/default_rules.html#no-changed-when
      shell: "timedatectl set-timezone {{ chrony_timezone }}"
