---
- hosts: all
  become: true
  tasks:
    - name: create /etc/rc.local on Ubuntu
      lineinfile:
        path: /etc/rc.local
        line: "#!/bin/sh -e"
        insertbefore: BOF
        mode: 0755
        create: yes

    - name: manage /etc/rc.local contents
      blockinfile:
        path: /etc/rc.local
        block: |
          {{ rc_local_contents | default('# ansible: rc_local_contents undefined') }}
        insertbefore: "^exit 0"
        mode: 0755
        create: yes

    - name: manage rc-local service
      systemd:
        name: rc-local
        state: started
        enabled: yes
