---
# Disable unattended upgrades because it kills Slurm running jobs unexpectedly.
# the apt package `unattended-upgrades` has been removed so is no longer necessary to disable parts of it.
- hosts: "{{ hostlist | default('all') }}"
  become: true
  tasks:
    - name: disable unattended upgrades
      lineinfile:
        dest: /etc/apt/apt.conf.d/10periodic
        regexp: "^APT::Periodic::Unattended-Upgrade"
        line: 'APT::Periodic::Unattended-Upgrade "0";'
