---
# Create user with password (defined in config/group_vars/all.yml)
- hosts: all

  become: true
  tasks:
    - name: Set backward compatible values for ssh-hardening if not defined
      block:
        # Fixed: [502] All tasks should be named
        - name: "set ssh_client_hardening false when undefined"
          set_fact:
            ssh_client_hardening: false
          when: ssh_client_hardening is undefined
        # Fixed: [502] All tasks should be named
        - name: "set ssh_server_password_login true when undefined"
          set_fact:
            ssh_server_password_login: true
          when: ssh_server_password_login is undefined
        # Fixed: [502] All tasks should be named
        - name: "set ssh_use_pam true when undefined"
          set_fact:
            ssh_use_pam: true
          when: ssh_use_pam is undefined
        # Fixed: [502] All tasks should be named
        - name: "set ssh_max_auth_retries 10 when undefined"
          set_fact:
            ssh_max_auth_retries: 10
          when: ssh_use_pam is undefined

    - name: Harden SSH
      include_role:
        name: dev-sec.ssh-hardening

    - name: Harden login.defs
      include_role:
        name: dev-sec.os-hardening

    - name: Set user ssh keys
      include_role:
        name: DeepOps.users
