---
- hosts: "{{ hostlist | default('all') }}"
  become: true
  tags:
    - nvidia
    - nvidia_docker
  tasks:
    - name: install custom facts module
      include_role:
        name: facts
      when: docker_install | default(true)

    - name: remove docker overrides, specifically to deal with conflicting options from DGX OS
      file:
        path: /etc/systemd/system/docker.service.d/docker-override.conf
        state: absent
      when: docker_install | default(true)

    - name: install nvidia-docker
      include_role:
        name: nvidia.nvidia_docker
      when:
        - docker_install | default(true)
        - (ansible_local['gpus'].count is defined and ansible_local['gpus']['count'])

  environment: "{{ proxy_env if proxy_env is defined else {} }}"
