---
- hosts: slurm-head
  tasks:
    - name: set controller fact
      set_fact:
        is_controller: true
      tags: always

- hosts: slurm-node
  tasks:
    - name: set compute fact
      set_fact:
        is_compute: true
      tags: always

- hosts: slurm-cluster
  become: true
  tasks:
    - name: set enroot DGX config fact
      set_fact:
        enroot_environ_config_files: "{{ enroot_environ_config_files_dgx }}"
      when: ansible_product_name is search("DGX")

- hosts: slurm-node
  become: true
  roles:
    - name: nvidia.enroot

- hosts: slurm-cluster
  become: true
  roles:
    - name: pyxis
