---
# Last playbook, last actions
- hosts: slurm-node-gpu[0]
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        # var: ansible_facts
        msg:
          - "logind_conf_runtime_directory_size: {{ logind_conf_runtime_directory_size }}"
          - "ansible_kernel: {{ ansible_kernel }}"
          - "ansible_distribution: {{ ansible_distribution }}"
          - "ansible_distribution_version: {{ ansible_distribution_version }}"
          - "ansible_architecture: {{ ansible_architecture }}"
