---
- name: Ubuntu | remove ppa
  ansible.builtin.apt_repository:
    repo: ppa:graphics-drivers/ppa
    state: absent

- name: Ubuntu | add pin file
  copy:
    src: "cuda-ubuntu.pin"
    dest: "/etc/apt/preferences.d/cuda-repository-pin-600"
    owner: "root"
    group: "root"
    mode: 0644

- name: Ubuntu | add key
  apt_key:
    url: "{{ nvidia_driver_ubuntu_cuda_repo_gpgkey_url }}"
    id: "{{ nvidia_driver_ubuntu_cuda_repo_gpgkey_id }}"
  # Fixed: [206] Variables should have spaces before and after: {{ var_name }}
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Ubuntu | add CUDA repo
  ansible.builtin.apt_repository:
    repo: "deb {{ nvidia_driver_ubuntu_cuda_repo_baseurl }} /"
    update_cache: yes
  # Fixed: [206] Variables should have spaces before and after: {{ var_name }}
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Ubuntu | install package
  ansible.builtin.apt:
    name: "datacenter-gpu-manager"
    state: "present"
  when: >
    nvidia_driver_force_install|default(false) or
    (
      cuda_playbook_install_driver|default(true) and
      ansible_local['gpus'].count is defined and
      ansible_local['gpus']['count']
    )
