---
- name: install DCGM from repos
  package:
    name: "datacenter-gpu-manager"
    state: present

- name: Ubuntu tasks
  include: install-ubuntu.yml

- name: Populate service facts
  service_facts:

- name: Start the nvidia-dcgm service when present (preferred)
  systemd:
    daemon_reload: yes
    name: "nvidia-dcgm.service"
    state: "started"
    enabled: true
  when: '"nvidia-dcgm.service" in services'

- name: Start the dcgm service otherwise
  systemd:
    daemon_reload: yes
    name: "dcgm.service"
    state: "started"
    enabled: true
  when: '"nvidia-dcgm.service" not in services'
