---
- name: install
  package:
    name: cachefilesd
    state: "{{ cachefilesd_package_state }}"

- name: enable
  template:
    src: cachefilesd.j2
    dest: /etc/default/cachefilesd
    mode: 0644

- name: configure
  template:
    src: cachefilesd-config.j2
    dest: /etc/cachefilesd.conf
    mode: 0644

- name: start
  service:
    name: cachefilesd
    state: restarted
    enabled: yes
