---
- include: ../container/docker.yml

- hosts: "{{ hostlist | default('all') }}"
  become: true
  tasks:
    - name: configure node exporter
      include_role:
        name: prometheus_node_exporter
