---
# Playbook designed to run a NCCL test across all nodes in a cluster
- hosts: slurm-head[0]
  vars:
    # Public repository for nccl performance/validation tests
    nccl_test_repo: "deepops/nccl-tests-tf20.06-ubuntu18.04:latest"
    num_gpus: 1 # e.g. a DGX A100 Server has 8 GPUs
    srun_command: |
      srun \
        -N {{ num_nodes }} \
        -G {{ num_nodes|int * num_gpus }} \
        --ntasks-per-node={{ num_gpus }} \
        --mpi=pmix \
        --exclusive  \
        --partition=a100 \
        --container-image={{ nccl_test_repo }} \
            all_reduce_perf \
            -b 1M \
            -e 4G \
            -f 2 \
            -g {{ num_gpus }}
  tasks:
    - name: Get node count from sinfo
      # noqa 301 https://ansible-lint.readthedocs.io/en/latest/default_rules.html#no-changed-when
      # Fixed: [306] Shells that use pipes should set the pipefail option
      shell: |
        set -o pipefail
        sinfo | tail -n +2  | awk '{sum += $4} END {print sum}'
      args:
        executable: /bin/bash
      register: node_out

    - name: Set num_nodes variable
      set_fact:
        num_nodes: "{{ node_out.stdout }}"
    - name: Set cmd variable
      set_fact:
        # Fixed [204] Lines should be no longer than 160 chars.
        cmd: "{{ srun_command }}"
    - name: Print node/gpu counts
      debug:
        msg:
          - "Detected {{ num_nodes }} nodes with {{ num_gpus }} gpus each."
          - "Proceeding to run validation test, this may take several minutes..."

    - name: Execute NCCL test across all nodes and GPUs
      # noqa 301 https://ansible-lint.readthedocs.io/en/latest/default_rules.html#no-changed-when
      # noqa 305 Use shell only when shell functionality is required
      shell: "{{ srun_command }}"
      args:
        executable: /bin/bash
      register: out
    - name: Print results
      debug:
        msg: "{{ out }}"
