# Deploy the Spack package manager
---
- hosts: "{{ hostlist | default('all') }}"
  become: true
  roles:
    - lmod

- hosts: "{{ hostlist | default('slurm-master[0]') }}"
  become: true
  roles:
    - spack
