---
- hosts: all
  become: true
  tasks:
    - name: Install NVIDIA Machine Learning packages
      include_role:
        name: nvidia_ml
  tags:
    - install

- hosts: all
  become: true
  tasks:
    - name: Remove NVIDIA Machine Learning packages
      include_role:
        name: nvidia_ml
      vars:
        nvidia_ml_package_state: absent
  tags:
    - never
    - remove
